package com.grammar.app.grammar_backend.service.ai;

public class PromptConstants {
    public static final String SYSTEM_CONTENT_GENERATION = "You are an expert English grammar teacher. You want to teach English grammar to students using games and exercises.";
    public static final String SYSTEM_CONTENT_VALIDATION = "You are a meticulous English grammar reviewer. You want to review the lesson content generated by the AI to ensure it is accurate for students to learn from.";
    public static final String USER_RULES =
                """
                Rules:
                - Keep them appropriate for the difficulty level
                - Make them realistic and relevant to the concept
                - Return valid JSON only with this schema:
                - No markdown fences.
                - No commentary.
                - No text before or after the JSON.
                - No code blocks.
                - No trailing commas.
                - The output must be a single JSON object.
                """;
    public static final String USER_EXERCISE_RULES =
            """
                    Exercise generation rules:
                    - Generate exactly one exercise.
                    - The exercise must directly assess the stated objective.
                    - The exercise must test one grammar point only.
                    - The exercise must have exactly one objectively correct answer.
                    - Avoid ambiguity, trick wording, and multiple valid interpretations.
                    - Keep the content realistic, natural, and appropriate for the difficulty level.
                    - Use clear, concise wording suitable for learners.
                    - The explanation must justify the answer using grammar reasoning, not just restate the answer.
                    - All fields must be internally consistent.
                    - The correctAnswer must exactly match the intended correct result in the exercise data.
                    - For MULTIPLE_CHOICE:
                      - Provide exactly 4 options
                      - Exactly 1 option must be correct
                      - Distractors must be plausible but clearly incorrect; do not include duplicate or near-duplicate options
                      - Do not include more than one grammatically valid answer
                      - The correctAnswer must exactly match one option in the options array
                      - The explanation must explain why the correct option is correct and why each other option is incorrect.
                    - For FILL_IN_THE_BLANK:
                      - Provide exactly 1 blank
                      - The sentence must contain enough context to determine the answer
                      - There must be exactly 1 valid correct answer
                      - Do not create blanks that allow multiple equally valid answers
                      - The correctAnswer must be the exact word or phrase that fills the blank
                      - The explanation must explain the grammar rule that makes the answer correct
                    - For TRUE_FALSE:
                      - The statement must be clearly true or clearly false
                      - Do not create statements that are partially true, debatable, or stylistic
                      - Focus on a single grammatical claim
                      - The correctAnswer must be either TRUE or FALSE
                      - The explanation must justify the truth value clearly
                      - If the statement is false, the explanation must include the corrected form or rule.
                    - For DRAG_AND_DROP:
                      - The task must clearly define what the learner is arranging or matching
                      - Every draggable item must be used exactly once
                      - There must be exactly 1 valid final arrangement or mapping
                      - Do not include items that could fit multiple positions equally well
                      - The correctAnswer must represent the one valid completed arrangement
                      - The explanation must describe the grammar rule or structure behind the arrangement.
                    - For SENTENCE_ORDERING: 
                      - Provide fragments or tokens that combine into exactly 1 correct sentence
                      - Do not allow multiple grammatical orderings
                      - The fragments must give enough information to reconstruct the sentence without guessing
                      - The correctAnswer must be the exact correctly ordered final sentence
                      - The explanation must explain why that order is grammatically correct
                      - Do not rely on punctuation or capitalization tricks unless they are the teaching objective.
            """;
    public static final String USER_CONTENT_SHAPE =
            """
            %s
            
            Concept:
                - Name: %s
                - Category: %s
                - Difficulty: %s
                - Goal: %s
            """;

}
